### ISSUE TITLE
Better Usage Example.

### ISSUE THREAD

**Issue by JimtotheB** [LichKing-2234/react-native-agora-rawdata#1]
From the Usage Example

```
await AgoraRawdata.registerVideoFrameObserver(
  await agora.getNativeHandle()
);
```

Now what? 

The expanded example here: https://github.com/LichKing-2234/react-native-agora-rawdata/blob/main/example/src/App.tsx

Seems like you are registering and unregistering handlers and then doing nothing else with them? How do we get access to the underlying frame data in Javascript?

The use case I'm after is capturing a single frame of video from the stream to upload to S3.

**Comment by LichKing-2234** [comment]
pls refer to the README

**Comment by hhemmati81** [comment]
@JimtotheB were you able to figure out how to pull a single frame from the video?
